flexelog/urls.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
from django.conf import settings
from django.urls import include, path, re_path
from django.views.static import serve
from flexelog import views



app_name = "flexelog"
urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/do_logout", views.do_logout, name="do_logout"),
    path("", views.index, name="index"),
    path("<str:lb_name>/", views.logbook_view, name="logbook"),
    path("<str:lb_name>/<int:entry_id>/", views.entry_detail, name="entry_detail"),
    # path("test/<str:lb_name>/<int:entry_id>/", views.test, name="test"),
    path("attachments/<str:lb_name>/<int:entry_id>/<str:filename>", views.attachments, name="attachments"),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

flexsite/urls.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
"""
URL configuration for flexsite project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("", include("flexelog.urls")),  # flexelog 'takes over' the root url
] 
if not settings.RUNNING_TESTS:
    urlpatterns += debug_toolbar_urls()

flexelog/views.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
from copy import copy
import logging
import operator
from pathlib import Path
from typing import Any
from django.conf import settings
from django.core.paginator import Paginator
from django.db import transaction 

from django.db.models.functions import Lower
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _

from flexelog.forms import EntryForm, EntryViewerForm, ListingModeFullForm, SearchForm, AttachmentFormSet
from flexelog.subst import apply_presets
from guardian.shortcuts import get_perms

from .models import Logbook, LogbookGroup, Entry
from .elog_cfg import get_config

from urllib.parse import unquote_plus

import logging
logger = logging.getLogger("flexelog")

# From https://stackoverflow.com/a/78769514/1987276
# only used occasionally in dev - add decorator around functions
# def query_debugger(view):
#     import time
#     from django.db import connection
#     def wrap(self, request, *args, **kwargs):
#         initial_queries = len(connection.queries)
#         start = time.time()
#         result = view(self, request, *args, **kwargs)
#         execution_time = time.time()-start
#         final_queries = len(connection.queries)
#         total_time = 0.0

#         print(f"==============> function : {view.__name__} made {final_queries - initial_queries} queries <========================")
#         for data in connection.queries:
#             print(f"\n({data['time']}) => {data['sql']}")
#             total_time += float(data['time'])
#         print(f"\n===============> Total : {total_time:.3f}(query), {round(execution_time,4)}(function) <==================\n")

#         return result
#     return wrap



def available_logbooks(request) -> list[Logbook]:
    return [
        lb
        for lb in Logbook.objects.filter(active=True).order_by("order")
        if not lb.auth_required
        or (request.user.is_authenticated and request.user.has_perm("view_entries", lb))
        or (not request.user.is_authenticated and not lb.is_unlisted)
    ]


def available_groups(logbooks: list[Logbook]):
    """Return dict of {group name: logbooks for that group}, group name is None if logbook in no groups"""
    groups = {}
    for group in LogbookGroup.objects.all():
        group_logbooks = [lb for lb in group.logbooks.all() if lb in logbooks]
        if group_logbooks:  # don't store it if has no logbooks in the group
            groups[group.name] = group_logbooks

    unassigned = [lb for lb in logbooks if not lb.logbookgroup_set.count()]
    if unassigned:
        groups[None] = unassigned
    return groups


def command_perm_response(request, command, commands, logbook, entry=None) -> HttpResponse | None:
    """Return an error message if the user is not allowed to <cmd> with this entry, else None"""
    # Note `entry`` only matters when editing/deleting one's own entries vs another author
    # If logbook does not require auth - anyone can do anything, 
    # except perhaps delete/edit after time period 
    def err(msg):
        return render(request, "flexelog/show_error.html", {"message": msg})

    def err_command(extra=""):
        msg = _('Error: Command "<b>%s</b>" not allowed') % command
        return err(msg + extra)

    def err_command_user():
        msg = _('Error: Command "<b>{command}</b>" is not allowed for user "<b>{user}</b>"').format(
                command=command,
                user = request.user.get_username()
        )
        return err(msg)

    # XX note - could possibly restrict defaults for no-auth logbook
    #   e.g. not allow deleting entries (but can use time restriction for that)

    if logbook.auth_required and not request.user.is_authenticated:
        return redirect(f"{settings.LOGIN_URL}?next={request.path}")

    perms = get_perms(request.user, logbook) if logbook.auth_required else [p[0] for p in logbook._meta.permissions]

    # If logbook is unlisted, then should look like doesn't exist to those without permissions
    if logbook.is_unlisted and not perms:
        return err(_('Logbook "%s" does not exist on remote server') % logbook.name)
    
    # Just viewing:
    if (not command or command == _("Find")):
        if 'view_entries' in perms:
            return None
        else:
            # From django admin translations
            msg = _(
                "You are authenticated as %(username)s, but are not authorized to access this "
                "page. Would you like to login to a different account?"
            ) % dict(username=request.user.get_username())
            # XX offer link to logout or login as other person  
            # logout_url =  reverse("flexelog:do_logout")
            # link = f'<a href="{logout_url}>{_("Logout")}</a>'
            return err(msg)  

    # if read-only logbook, cannot do anything other than viewing-type commands
    if logbook.readonly:
        extra = "&nbsp;&nbsp;" + _('Logbook "%s" is read-only') % logbook.name
        return err_command(extra)
 
    if command not in commands:
        return err_command()

    if command in (_("New"), _("Reply"), _("Duplicate")) and "add_entries" in perms:
        return None
    
    # Only 'edit' and 'delete' left, check user permissions first
    can_edit = 'edit_own_entries' in perms or 'edit_others_entries' in perms
    can_delete = 'delete_own_entries' in perms or 'delete_others_entries' in perms
    if (command == _("Edit") and not can_edit) or (command == _("Delete") and not can_delete):
        return err_command_user()
    
    # Now need to check entry vs author
    if entry is None:
        return None  # will have to deal with after POST or something

    if entry.author and request.user != entry.author:
        # XX below messages not quite true.  Some others might be able to edit the entry, just not current one
        # proper message would be 'you do not have rights to edit another user's entry' (in this logbook)
        if command==("Edit") and 'edit_others_entries' not in perms:
            return err(_("Only user <b>%s</b> can edit this entry") % entry.author.get_username())
        if command==("Delete") and 'delete_others_entries' not in perms:
            return err(_("Only user <b>%s</b> can delete this entry") % entry.author.get_username())
    elif (
        (command == _("Edit") and 'edit_own_entries' not in perms) 
        or (command == _("Delete") and 'delete_own_entries' not in perms)
    ):
        return err_command_user()
    
    # User has permission, in general, but now see if time-restricted
    cfg = get_config()
    restrict_hours = cfg.get(logbook, "Restrict edit time", valtype=float)
    if not restrict_hours:
        return None

    timediff = timezone.now() - entry.date   # XXX timezone differences?   
    if timediff.total_seconds > restrict_hours * 60 * 60:
        msg = _("Entry can only be edited %1.2lg hours after creation") % restrict_hours
        return err(msg)

    return None


def get_param(
    request, key: str, *, valtype: type = str, default: Any = None, force_single=True
) -> Any:
    """Return the GET query value for key, but default if not found or not of right type

    get_single only affects what happens if a value in the query string is repeated.
    If True, it is standard Django 'get' behaviour - the last value is returned.

    If any value of the parameter can't be converted to `valtype`, then `default` is returned.
    """
    if force_single:
        val = request.GET.get(key, default)
        if val == default:
            return val
        try:
            return valtype(val)
        except ValueError:
            return default

    val = request.GET.getlist(key, default)
    if len(val) == 0 or val == default:
        return default
    try:
        val = [valtype(x) for x in val]
    except ValueError:
        val = default

    return val[0] if len(val) == 1 else val



def do_logout(request):
    return render(request, "flexelog/do_logout.html")


def attachments(request, lb_name, id, filename):
    return render(request, "flexelog/show_error.html", {"message": _("Not Implemented")})

def index(request):
    # XXX need to check Protect Selection page whether the list is shown only to registered users,
    #   (or do equivalent permissions "view logbook index" or similar)
    # OR Selection page = <file> / Guest Selection page = <file> equiv (latter if 'global' password file used in PSI elog)
    # Welcome Title = <html code> equivalent needed
    # Page title from [global] section
    #
    cfg = get_config()
    logbooks = available_logbooks(request)
    context = dict(
        cfg=cfg,
        group_logbooks=available_groups(logbooks),
        heading="FlexElog Logbook Selection",
        cfg_css=cfg.get(
            "global", "css", valtype=str, default=""
        ),  # XXX admin forces global since lb can't exist
    )
    return render(request, "flexelog/index.html", context)


def logbook_post(request, logbook):
    """Handle POST to logbook page - can be New, Reply, Edit form results"""
    # XX auth - need to confirm user can New or Reply or Edit or Delete

    cfg = get_config()
    if request.POST.get("cmd") in (_("Submit"), _("Save")):
        page_type = request.POST["page_type"]
        attr_names = request.POST["attr_names"].split(",")
        lb_attrs = cfg.lb_attrs[logbook.name]
        form = EntryForm(data=request.POST, lb_attrs=lb_attrs)
        if page_type == "Edit":
            # need entry for AttachmentFormSet to figure out changes
            entry = Entry.objects.get(lb=logbook, id=request.POST.get("edit_id"))  # XXX catch errors
        else:
            entry = None  # fill in later
        attachment_formset = AttachmentFormSet(request.POST, request.FILES, instance=entry)

flexelog/templates/flexelog/include/attachments.html
{% load flex %}
{% load i18n %}

{{ attachment_formset.management_form }}
<table id="attachments_table" class="frame" width="100%" cellpadding="0" cellspacing="0">
<!-- table width="100%" border="0" cellpadding="0" cellspacing="0" -->
    {# Display existing attachment #}
    
    {% for attachment_form in attachment_formset %}
    {% with attachment_form.instance as attachment %}
    {% if attachment.pk %} {# existing attachment #}
        {% comment %} <tr><td>
        <table width="100%" cellpadding="0" cellspacing="0">
        {% endcomment %}
        <tr>
        <td nowrap width="10%" class="attribname">{% translate "Attachment" %} {{ forloop.counter }}:</td>
        {% if attachment.attachment_file %}
            <td nowrap width="20%" class="attribvalue"><a href="{{ attachment.attachment_file.url }}" target="_blank">
            {{ attachment.display_filename }}</a>
            {% if attachment.file_exists %} &nbsp;<span class="bytes">{{ attachment.attachment_file.size|filesizeformat }}</span>
            {% endif %}
            </td>
            <td class="attribvalue">
            {% if editing %}
            <small class="text-muted">{% translate "Replace file" %}:</small>
            {{ attachment_form.attachment_file }} {# This allows uploading a new file #}
            &nbsp;&nbsp;{{ attachment_form.DELETE }}
            <label class="form-check-label" for="{{ attachment_form.DELETE.id_for_label }}"">{% translate "Delete" %}</label>
            {% endif %}
            </td>
        
            {% if attachment.is_viewable %}
            <tr><td colspan="3">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                    {% if attachment.is_image %}
                        <td class="attachmentframe"><img src="{{ attachment.attachment_file.url }}"  /></td>
                    {% else %}
                        <td class="messageframe"><object id="frame" class="object_preview" data="{{ attachment.attachment_file.url }}"></object></td>
                    {% endif %}
                    </tr>
                </table>
            </td></tr>
            {% endif %}
    

        {% else %}  {# does this ever get used? - it shouldn't #}
            <td nowrap width="20%" class="attribvalue">
            {% translate "No file uploaded" %}
            <small class="text-muted">Upload file:</small>
            {{ attachment_form.file }} {# This allows uploading a new file where none existed #}
            </td>
        {% endif %}
                
        {{ attachment_form.id }} {# Hidden input for instance #}
        {{ attachment_form.attachment_file.as_hidden }} {# existing file path hidden #}
        {% comment %} </tr>   
        </table>
        </td></tr>
        {% endcomment %}
    {% elif editing and not attachment.pk %}
        {% comment %} <table width="100%" cellpadding="0" cellspacing="0"> {% endcomment %}
        <tr>
            <td nowrap width="10%" class="attribname">{% translate "New Attachment" %}</td>
            <td nowrap width="20%" class="attribvalue">
                {# {{ attachment_form.attachment_file.label_tag }} #}
                {{ attachment_form.attachment_file }}
                {% if attachment_form.attachment_file.errors %}<div class="text-danger">{{ attachment_form.attachment_file.errors }}</div>{% endif %}
            </td>
            <td class="attribvalue">{{ attachment_form.id.as_hidden }}</td>
        </tr>
    {% comment %} </table> {% endcomment %}
    {% endif %}
    {% endwith %}    
    {% endfor %}

</table>
    {% comment %}
    <tr><td>
        <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
            <td nowrap width="10%" class="attribname">{% translate "Attachment" %} {{ forloop.counter }}:</td>
            <td class="attribvalue"><a href="{{ attachment.attachment_file.url }}">{{ attachment.display_filename }}</a>
                &nbsp;<span class="bytes">{{ attachment.attachment_file.size|filesizeformat }}</span></td>
            </tr>   
        </table>
    </td></tr>
    <tr><td>
        <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
            {% if attachment.is_image %}
                <td class="attachmentframe"><img src="{{ attachment.attachment_file.url }}" height="200px" /></td>
            {% else %}
                <td class="messageframe"><object id="frame" data="{{ attachment.attachment_file.url }}"></object></td>
            {% endif %}
            </tr>
        </table>
    </td></tr>

    {% endfor %}


   {% if editing %}
    <tr><td>
        <table width="100%" cellpadding="0" cellspacing="0">
        {% for i in attachment_slots %}
        <tr>
        <td nowrap class="attribname">{% translate "Attachment" %} {{ i }}:</td>
        <td class="attribvalue"><input type="file" size="60" maxlength="200" name="attfile{{i}}"></td>
        </tr>
        {% endfor %}
        </table>
    </td></tr>
   {% endif %}
    
    {% endcomment %}

flexelog/templates/flexelog/include/commands.html
{# available commands and their urls #}
<tr>
    <td class="menuframe">
        <span class="menu1">
            {% for cmd in commands %}
            &nbsp;<a href="{{ cmd.1 }}">{{ cmd.0 }}</a>&nbsp;
            {% if not forloop.last %}|{% endif %}
            {% endfor %}
        </span>
    </td>
    
</tr>

flexelog/templates/flexelog/include/editor_tui.html
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css">
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/chart/latest/toastui-chart.min.css">
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism.min.css">
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/editor-plugin-color-syntax/latest/toastui-editor-plugin-color-syntax.min.css">
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight.min.css">
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/editor-plugin-table-merged-cell/latest/toastui-editor-plugin-table-merged-cell.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<script src="https://uicdn.toast.com/chart/latest/toastui-chart.min.js"></script>
<script src="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.min.js"></script>
<script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
<script src="https://uicdn.toast.com/editor-plugin-chart/latest/toastui-editor-plugin-chart.min.js"></script>
<script src="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight-all.min.js"></script>
<script src="https://uicdn.toast.com/editor-plugin-color-syntax/latest/toastui-editor-plugin-color-syntax.min.js"></script>
<script src="https://uicdn.toast.com/editor-plugin-table-merged-cell/latest/toastui-editor-plugin-table-merged-cell.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>

<script language="javascript" type="text/javascript">
    function chkform() {
        // if (last_key == 13) {
        //     var ret = confirm('Really submit this entry?');
        //     if (!ret) {
        //         last_key = 0;
        //         return false;
        //     }
        // }
        try {
        if (document.form1.Subject.value == "") {
            alert("Please enter attribute 'Subject'");
            document.form1.Subject.focus();
            return false;
        }
        }
        catch(err) {
        }
        
        
        
        // if (autoSaveTimer != null)
        // clearTimeout(autoSaveTimer);
        // submitted = true;
        
        document.getElementById("editor_markdown").value = editor.getMarkdown();
        document.getElementById("editor_html").value = editor.getHTML();
    
        return true;
    }
</script>

flexelog/templates/flexelog/include/entry_list_core.html
{% load flex %}
{% load i18n %}

{% include "flexelog/include/pagination.html" %}

<tr><td>
<table class="listframe" width="100%" cellspacing=0>
{% include "flexelog/include/list_display_header.html"%}
{% for entry in page_obj %}
    {% cycle '2' '1' as listX silent %}
    {% entry_listing entry columns selected_id filter_attrs casesensitive mode listX forloop.counter %}
{% endfor %}
</table>
{% include "flexelog/include/pagination.html" %}
{% if not page_obj %}
<tr><td class="errormsg">{% translate 'No entries found' %}</td></tr>
{% endif %}
</td></tr>

flexelog/templates/flexelog/include/filter_attrs.html
{% load flex %}

{% if filters %}
    <tr><td class="listframe">
    <table width="100%" border="0" cellpadding="0" cellspacing="0">
    {% for name, val in filters.items %}
      <tr><td nowrap width="10%" class="attribname">{{ name }}:</td>
      <td class="attribvalue">{{ val|highlight:val }}</td></tr>
    {% endfor %}
    </table>
    </td></tr>
{% endif %}

flexelog/templates/flexelog/include/lb_tabs.html
{% load i18n %}
{% load static %}

{% block more_head_links %}
  {% if cfg_css %}
    {% with 'flexelog/'|add:cfg_css as static_link %}
      <link rel="stylesheet" type="text/css" href="{% static static_link %}">
    {% endwith %}
  {% endif %}
{% endblock %}
{# Table containing tabs and comment bar #}
{# Logbook tabs across the top #}
{% if group_tabs %}
    <tr><td class="gtabs">
    {% for group_name, group_url in group_tabs %}
      <span class="{% if group_name == selected_group %}s{% endif %}gtab">
        <a href="{{ group_url }}" hx-boost="true">{{ group_name }}</a></span>
    {% endfor %}
      </td></tr>
{% endif %}
<tr>
    <td class="tabs">
    {% if main_tab %}
      <span class="ltab">
        <a href="{% url 'flexelog:index' %}">{{ main_tab }}</a>
      </span>
    {% endif %}
    {% for lb in logbooks %}
      <span class="{% if lb.name == logbook.name %}s{% endif %}ltab">
        <a href="{% url 'flexelog:logbook' lb.name %}" title="{{ lb.comment }}" hx-boost="true">{{ lb.name }}</a>
      </span>
    {% endfor %}
    </td>
</tr>

{# Bar for this logbook comment #}
<tr><td>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr><td class="title1">&nbsp;&nbsp;{{ logbook.comment }}
    {% if page_n_of_N %}
        {% if logbook.comment %}, {% endif %}{{ page_n_of_N }}
    {% endif %}
    &nbsp;</td>
    {% if request.user.is_authenticated %}
      <td class="title2">{% translate "Logged in as" %} "{{ request.user.get_username }}"&nbsp;
        &nbsp;&nbsp;<a href="{% url 'flexelog:do_logout' %}">{% translate "Logout" %}</a>
        {% if request.user.is_staff %}
          &nbsp;&nbsp;<a href="{% url 'admin:index' %}">{% translate "Admin" %}</a>
        {% endif %}
      </td>


    {% endif %}
  </tr>
</table>
</td></tr>

flexelog/templates/flexelog/include/list_display_header.html
  {% load static %}
  {% load i18n %}
  <tr>
    {% for col_name, col_field in columns.items %}
    {# XX need urlencoded version of col_name for url #}
    {% if col_field == "text" %}
      {% if mode == "summary" %}
        <th class="listtitle2">
            {{ col_name }}&nbsp;&nbsp;&nbsp;
            <input id="search" type="search" name="text" size="8"
                value="{{ text }}"
                hx-get="{% querystring %}"
                hx-trigger="search, keyup delay:700ms changed"
                hx-target="body"/>
            {% comment %} <input type="submit" value="{% translate 'Find' %}"/> {% endcomment %}
        </th>
      {% endif %}
    {% elif col_field == "attachments" %}
      {% if mode == "summary" %}
        <th class="listtitle3"><img src="{% static 'flexelog/attachment.png' %}" alt="{% translate 'Attachments'}" title="{% translate 'Attachments'}"</th>
      {% endif %}
    {% else %}
      <th class="listtitle">  
      {% if col_field == sort_attr_field %}
        {% if is_rsort %}
          <a href="{% querystring sort=col_name rsort=None %}">{{ col_name }}&nbsp;↓</a>
        {% else %}
          <a href="{% querystring rsort=col_name sort=None %}">{{ col_name }}&nbsp;↑</a>
        {% endif %}
      {% else %}
        <a href="{% querystring sort=col_name rsort=None %}">{{ col_name }}</a>
      {% endif %}
      </th>
    {% endif %}
    {% endfor %}
    
  </tr>

flexelog/templates/flexelog/include/list_modes.html
{% load i18n %}
<tr>
  <td class="menuframe">
    <table width="100%" border=0 cellpadding="0" cellspacing="0">
      <tr>
        <td class="menu2a">
          {% for mode in modes %}
          {% if mode.0 == current_mode %}
          &nbsp;{{ mode.0 }}&nbsp;
          {% else %}
          &nbsp;<a href="{% querystring mode=mode.1 %}">{{ mode.0 }}</a>&nbsp;
          {% endif %}
          {% if not forloop.last %}|{% endif %}
          {% endfor %}

        <td class="menu2b">
          {% comment %}
          <a href="?new_entries=1"><img align="middle" border="0" src="new_entry.png" alt="Show only new entries"
              title="Show only new entries"></a>
          {% endcomment %}
          &nbsp;&nbsp;&nbsp;
          {% if page_obj %}<b>{{ page_obj.paginator.count }} {% translate "Entries" %}</b>&nbsp;{% endif %}
        </td>

      </tr>
    </table>
  </td>
</tr>

flexelog/templates/flexelog/include/pagination.html
{% load i18n %}

{% if page_obj.has_other_pages %}

<tr><td class="menuframe"><span class="menu3">

{% translate "Goto page" %}
{% if page_obj.has_previous %}
  <a href="{% querystring page=page_obj.previous_page_number id=None %}">{% translate "Previous" %}</a>
{% endif %}
{% for i in page_range %}
  {% if page_obj.number == i %}
    {{ i }}
  {% elif i == page_obj.paginator.ELLIPSIS %}
    &nbsp;...&nbsp;
  {% else %}
    <a href="{% querystring page=i id=None %}">{{ i }}</a>
  {% endif %}
  {% if not forloop.last and not i == page_obj.paginator.ELLIPSIS %}, {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  &nbsp;&nbsp;<a href="{% querystring page=page_obj.next_page_number id=None%}">{% translate "Next" %}</a>
{% endif %}

&nbsp;&nbsp;<a href="{% querystring page='all' npp=None id=None %}">{% translate "All" %}</a>


</span>
</td></tr>

{% endif %}