flexelog/urls.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
from django.conf import settings
from django.urls import include, path, re_path
from django.views.static import serve
from flexelog import views



app_name = "flexelog"
urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/do_logout", views.do_logout, name="do_logout"),
    path("", views.index, name="index"),
    path("<str:lb_name>/", views.logbook_view, name="logbook"),
    path("<str:lb_name>/<int:entry_id>/", views.entry_detail, name="entry_detail"),
    # path("test/<str:lb_name>/<int:entry_id>/", views.test, name="test"),
    path("attachments/<str:lb_name>/<int:entry_id>/<str:filename>", views.attachments, name="attachments"),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

flexsite/urls.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
"""
URL configuration for flexsite project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("", include("flexelog.urls")),  # flexelog 'takes over' the root url
] 
if not settings.RUNNING_TESTS:
    urlpatterns += debug_toolbar_urls()

flexelog/views.py
# Copyright 2025 flexelog authors. See LICENSE file for details.
from copy import copy
import logging
import operator
from pathlib import Path
from typing import Any
from django.conf import settings
from django.core.paginator import Paginator
from django.db import transaction 

from django.db.models.functions import Lower
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _

from flexelog.forms import EntryForm, EntryViewerForm, ListingModeFullForm, SearchForm, AttachmentFormSet
from flexelog.subst import apply_presets
from guardian.shortcuts import get_perms

from .models import Logbook, LogbookGroup, Entry
from .elog_cfg import get_config

from urllib.parse import unquote_plus

import logging
logger = logging.getLogger("flexelog")

# From https://stackoverflow.com/a/78769514/1987276
# only used occasionally in dev - add decorator around functions
# def query_debugger(view):
#     import time
#     from django.db import connection
#     def wrap(self, request, *args, **kwargs):
#         initial_queries = len(connection.queries)
#         start = time.time()
#         result = view(self, request, *args, **kwargs)
#         execution_time = time.time()-start
#         final_queries = len(connection.queries)
#         total_time = 0.0

#         print(f"==============> function : {view.__name__} made {final_queries - initial_queries} queries <========================")
#         for data in connection.queries:
#             print(f"\n({data['time']}) => {data['sql']}")
#             total_time += float(data['time'])
#         print(f"\n===============> Total : {total_time:.3f}(query), {round(execution_time,4)}(function) <==================\n")

#         return result
#     return wrap



def available_logbooks(request) -> list[Logbook]:
    return [
        lb
        for lb in Logbook.objects.filter(active=True).order_by("order")
        if not lb.auth_required
        or (request.user.is_authenticated and request.user.has_perm("view_entries", lb))
        or (not request.user.is_authenticated and not lb.is_unlisted)
    ]


def available_groups(logbooks: list[Logbook]):
    """Return dict of {group name: logbooks for that group}, group name is None if logbook in no groups"""
    groups = {}
    for group in LogbookGroup.objects.all():
        group_logbooks = [lb for lb in group.logbooks.all() if lb in logbooks]
        if group_logbooks:  # don't store it if has no logbooks in the group
            groups[group.name] = group_logbooks

    unassigned = [lb for lb in logbooks if not lb.logbookgroup_set.count()]
    if unassigned:
        groups[None] = unassigned
    return groups


def command_perm_response(request, command, commands, logbook, entry=None) -> HttpResponse | None:
    """Return an error message if the user is not allowed to <cmd> with this entry, else None"""
    # Note `entry`` only matters when editing/deleting one's own entries vs another author
    # If logbook does not require auth - anyone can do anything, 
    # except perhaps delete/edit after time period 
    def err(msg):
        return render(request, "flexelog/show_error.html", {"message": msg})

    def err_command(extra=""):
        msg = _('Error: Command "<b>%s</b>" not allowed') % command
        return err(msg + extra)

    def err_command_user():
        msg = _('Error: Command "<b>{command}</b>" is not allowed for user "<b>{user}</b>"').format(
                command=command,
                user = request.user.get_username()
        )
        return err(msg)

    # XX note - could possibly restrict defaults for no-auth logbook
    #   e.g. not allow deleting entries (but can use time restriction for that)

    if logbook.auth_required and not request.user.is_authenticated:
        return redirect(f"{settings.LOGIN_URL}?next={request.path}")

    perms = get_perms(request.user, logbook) if logbook.auth_required else [p[0] for p in logbook._meta.permissions]

    # If logbook is unlisted, then should look like doesn't exist to those without permissions
    if logbook.is_unlisted and not perms:
        return err(_('Logbook "%s" does not exist on remote server') % logbook.name)
    
    # Just viewing:
    if (not command or command == _("Find")):
        if 'view_entries' in perms:
            return None
        else:
            # From django admin translations
            msg = _(
                "You are authenticated as %(username)s, but are not authorized to access this "
                "page. Would you like to login to a different account?"
            ) % dict(username=request.user.get_username())
            # XX offer link to logout or login as other person  
            # logout_url =  reverse("flexelog:do_logout")
            # link = f'<a href="{logout_url}>{_("Logout")}</a>'
            return err(msg)  

    # if read-only logbook, cannot do anything other than viewing-type commands
    if logbook.readonly:
        extra = "&nbsp;&nbsp;" + _('Logbook "%s" is read-only') % logbook.name
        return err_command(extra)
 
    if command not in commands:
        return err_command()

    if command in (_("New"), _("Reply"), _("Duplicate")) and "add_entries" in perms:
        return None
    
    # Only 'edit' and 'delete' left, check user permissions first
    can_edit = 'edit_own_entries' in perms or 'edit_others_entries' in perms
    can_delete = 'delete_own_entries' in perms or 'delete_others_entries' in perms
    if (command == _("Edit") and not can_edit) or (command == _("Delete") and not can_delete):
        return err_command_user()
    
    # Now need to check entry vs author
    if entry is None:
        return None  # will have to deal with after POST or something

    if entry.author and request.user != entry.author:
        # XX below messages not quite true.  Some others might be able to edit the entry, just not current one
        # proper message would be 'you do not have rights to edit another user's entry' (in this logbook)
        if command==("Edit") and 'edit_others_entries' not in perms:
            return err(_("Only user <b>%s</b> can edit this entry") % entry.author.get_username())
        if command==("Delete") and 'delete_others_entries' not in perms:
            return err(_("Only user <b>%s</b> can delete this entry") % entry.author.get_username())
    elif (
        (command == _("Edit") and 'edit_own_entries' not in perms) 
        or (command == _("Delete") and 'delete_own_entries' not in perms)
    ):
        return err_command_user()
    
    # User has permission, in general, but now see if time-restricted
    cfg = get_config()
    restrict_hours = cfg.get(logbook, "Restrict edit time", valtype=float)
    if not restrict_hours:
        return None

    timediff = timezone.now() - entry.date   # XXX timezone differences?   
    if timediff.total_seconds > restrict_hours * 60 * 60:
        msg = _("Entry can only be edited %1.2lg hours after creation") % restrict_hours
        return err(msg)

    return None


def get_param(
    request, key: str, *, valtype: type = str, default: Any = None, force_single=True
) -> Any:
    """Return the GET query value for key, but default if not found or not of right type

    get_single only affects what happens if a value in the query string is repeated.
    If True, it is standard Django 'get' behaviour - the last value is returned.

    If any value of the parameter can't be converted to `valtype`, then `default` is returned.
    """
    if force_single:
        val = request.GET.get(key, default)
        if val == default:
            return val
        try:
            return valtype(val)
        except ValueError:
            return default

    val = request.GET.getlist(key, default)
    if len(val) == 0 or val == default:
        return default
    try:
        val = [valtype(x) for x in val]
    except ValueError:
        val = default

    return val[0] if len(val) == 1 else val



def do_logout(request):
    return render(request, "flexelog/do_logout.html")


def attachments(request, lb_name, id, filename):
    return render(request, "flexelog/show_error.html", {"message": _("Not Implemented")})

def index(request):
    # XXX need to check Protect Selection page whether the list is shown only to registered users,
    #   (or do equivalent permissions "view logbook index" or similar)
    # OR Selection page = <file> / Guest Selection page = <file> equiv (latter if 'global' password file used in PSI elog)
    # Welcome Title = <html code> equivalent needed
    # Page title from [global] section
    #
    cfg = get_config()
    logbooks = available_logbooks(request)
    context = dict(
        cfg=cfg,
        group_logbooks=available_groups(logbooks),
        heading="FlexElog Logbook Selection",
        cfg_css=cfg.get(
            "global", "css", valtype=str, default=""
        ),  # XXX admin forces global since lb can't exist
    )
    return render(request, "flexelog/index.html", context)


def logbook_post(request, logbook):
    """Handle POST to logbook page - can be New, Reply, Edit form results"""
    # XX auth - need to confirm user can New or Reply or Edit or Delete

    cfg = get_config()
    if request.POST.get("cmd") in (_("Submit"), _("Save")):
        page_type = request.POST["page_type"]
        attr_names = request.POST["attr_names"].split(",")
        lb_attrs = cfg.lb_attrs[logbook.name]
        form = EntryForm(data=request.POST, lb_attrs=lb_attrs)
        if page_type == "Edit":
            # need entry for AttachmentFormSet to figure out changes
            entry = Entry.objects.get(lb=logbook, id=request.POST.get("edit_id"))  # XXX catch errors
        else:
            entry = None  # fill in later
        attachment_formset = AttachmentFormSet(request.POST, request.FILES, instance=entry)

flexelog/templates/flexelog/base.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load django_htmx %}

<!DOCTYPE html>
<html>
<head>
    <meta name="ROBOTS" content="NOINDEX, NOFOLLOW">
        <title>{% block title %}FlexElog{% endblock %}</title>     
    </meta>
    {% htmx_script %}
    <link rel="stylesheet" type="text/css" href="{% static 'flexelog/elog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'flexelog/flexelog.css' %}">
    <link rel="shortcut icon" href="{% static 'flexelog/favicon.ico' %}">
    <link rel="icon" href="{% static 'flexelog/favicon.png' %}" type="image/png">
    {% if cfg_css %}
        {% with 'flexelog/'|add:cfg_css as static_link %}
        <link rel="stylesheet" type="text/css" href="{% static static_link %}">
        {% endwith %}
    {% endif %}
    {% block more_head_links %}{% endblock %}
</head>

<body hx-headers='{"x-csrftoken": "{{ csrf_token }}"}'>
  {% block body %}{% endblock %}
</body>
</html>

flexelog/templates/flexelog/confirmation.html
{% extends "flexelog/base.html" %}
{% load i18n %}

{% block title %}Fl'og {{ title }}{% endblock title %}
{% block more_head_links %}
 {{ form.media }}

{% endblock more_head_links %}

{% block body %}
<form name="form1" method="{{ method }}" action="{{ action }}">
    {% if method == "POST" %}{% csrf_token %}{% endif %}
    <input type=hidden name=cmd value="{{ cmd }}">
    <table class="dlgframe" cellspacing="0" align="center">
        <tr>
            <td class="dlgtitle">{{ prompt }}</td>
        </tr>
        <tr>
            <td align=center class="dlgform">{{ message }}</td>
        </tr>
        <tr>
            <td align=center class="dlgform">
                <input type="submit" name="confirm" value="{{ true_label }}">
                <input type=submit name="confirm" value="{{ false_label }}">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

flexelog/templates/flexelog/do_logout.html
{% extends "flexelog/base.html" %}
{% load i18n %}

{% block body %}
  
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <table class="login_frame" cellspacing=0 align=center>
      {% if user.is_authenticated %}
        <tr><td class="login_title">
          {% translate 'Login name' %}: {{ user.get_username }}
        </td></tr>
        <tr><td class="login_form">
          <button type="submit">{% translate 'Logout' %}</button>
        </td></tr>
      {% else %}
        <tr><td class="login_form">{% translate 'Not logged in' %}</td></tr>
        <tr><td class="login_form"><a href="{% url 'login' %}">{% translate 'Login' %}</a></td></tr>
      </table>
  </form>

{% endif %}
{% endblock %}

flexelog/templates/flexelog/edit.html
{% extends "flexelog/base.html" %}
{% load i18n %}

{% block title %}Fl'og {{ entry.attrs.subject }}{% endblock title %}
{% block more_head_links %}
 {{ form.media }}

{% endblock more_head_links %}

{% block body %}
<form name="form1" method="POST" action="{% url 'flexelog:logbook' logbook.name %}" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="frame" cellpadding="0" cellspacing="0">
  {% include "flexelog/include/lb_tabs.html" %}
  <table class="listframe" width="100%" cellspacing="0" cellpadding="0">
    <tr>
    <td class="attribhead">
        {% translate 'Message ID' %}:&nbsp;<b>{{ entry.id }}</b>
        &nbsp;&nbsp;&nbsp;&nbsp;{% translate 'Entry time' %}:&nbsp;<b>{{ entry.date }}</b>
        {% if entry.author %}&nbsp;&nbsp;{% translate 'Username' %}:&nbsp;<b>{{ entry.author.get_username }}</b>{% endif %}
    </td>
    </tr>
    {% if entry.last_modified_date %}
    <tr><td class="attribhead">{% translate 'Last submission' %}:&nbsp;{% translate 'Entry time' %}:&nbsp;<b>{{ entry.last_modified_date }}</b>
    {% if entry.last_modified_author %}&nbsp;&nbsp;{% translate 'Username' %}:&nbsp;<b>{{ entry.last_modified_author.get_username }}</b>{% endif %}
    {% endif %}</td></tr>

    <tr><td class="menuframe"><span class="menu1">
        <input type="submit" name="cmd" value="{% translate 'Submit' %}" onclick="return chkform();">
        {# <input type="submit" name="cmd" value="Delete" onclick="return check_delete();"> #}
        &nbsp;&nbsp;
        </span></td></tr>
        <tr><td>
        <table class="listframe" width="100%" cellspacing="0" cellpadding="0">
        {# XX make required field thing show only when any are required #}
        
        {% if Required %}<tr><td colspan="2" class="attribvalue">
            {% translate "Fields marked with" %}<font color="red"> * </font>
            {% translate "are required" %}
        </td></tr>{% endif %}
    <tr>
    <td>
    <table width="100%" cellpadding="0" cellspacing="0">
        {% comment %} {% for attr, val in entry.attrs.items %} {% endcomment %}
        {% if errors %}
        <tr>
          <td colspan="2">
            {{ errors }}
            {% if not fields %}
              {% for field in hidden_fields %}{{ field }}{% endfor %}
              
            {% endif %}
          </td>
        </tr>
      {% endif %}
      {% for field, errors in fields %}
       
        <tr{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
            {% if field.label != "Text" %}<th class="attribname" nowrap>
                {% if field.label %}{{ field.label_tag }}{% endif %}
                {% if field.label|lower in Required %}<font color=red>*</font>{% endif %}</th>
                <td class="attribvalue">
                {{ errors }}
                {{ field }}
                {% if field.help_text %}
                <br>
                <span class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</span>
                {% endif %}
            {% endif %}
            {% if forloop.last %}
              {% for field in hidden_fields %}{{ field }}
              {% endfor %}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      {% if not fields and not errors %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
      
    </table>
    </td>
    </tr>

    {# EDITOR/VIEWER #}
    <tr>
    <td class="messageframe">
        {# XX kludge, not sure correct syntax to get text field directly #}
        {% for field, errors in fields %}
            {% if field.label == "Text" %}{{ field }}{% endif %}
        {% endfor %}
    </td>
    </tr>

  </table>
</table>

{% with editing=1 %}
{% include "flexelog/include/attachments.html" %}
{% endwith %}
</form>

<script language="javascript" type="text/javascript">
function latexPlugin() {
    const toHTMLRenderers = {
        latex(node) {
            const html = katex.renderToString(node.literal);

            return [
                { type: 'openTag', tagName: 'div', outerNewLine: true },
                { type: 'html', content: html },
                { type: 'closeTag', tagName: 'div', outerNewLine: true }
            ];
        }
    }
    return { toHTMLRenderers };
}
    
{% comment %} const { Editor } = toastui;
const { chart, codeSyntaxHighlight, colorSyntax, tableMergedCell } = Editor.plugin;

const editor = new Editor({
    el: document.querySelector('#editor'),
    previewStyle: 'vertical',
    height: '500px',
    initialValue: '',
    usageStatistics: false,
    mathSupport: true,
    placeHolder: 'Enter your text',
    autofocus: false,
    plugins: [[chart, {maxWidth:750, maxHeight:500}], [codeSyntaxHighlight, {highlighter: Prism}], colorSyntax, tableMergedCell, latexPlugin],
});

function body_onload() {            
    var text = document.getElementById("editor_markdown").value;
    editor.setMarkdown(text);
    return true;
} {% endcomment %}
</script>
{% endblock body %}

flexelog/templates/flexelog/entry_detail.html
{% extends "flexelog/base.html" %}
{% load flex %}
{% load i18n %}

{% block title %}Fl'og {{ entry.attrs.subject }}{% endblock title %}
{% block more_head_links %}
 {{ form.media }}
{% endblock more_head_links %}

{% block body %}
<form name="form1" method="GET" action="{% url 'flexelog:entry_detail' logbook.name entry.id %}">
{# <input type="hidden" name="page_type" value="{{ page_type }}" /> #}
<table class="frame" cellpadding="0" cellspacing="0">
  {% include "flexelog/include/lb_tabs.html" %}
  {% include "flexelog/include/commands.html" %}
  <tr><td>
  <table class="listframe" width="100%" cellspacing="0" cellpadding="0">
    {% if entry.replies.count or entry.in_reply_to %}
      <tr><td>
        <table width="100%" border="0" cellpadding="0" cellspacing="0">
            {% thread_tree entry %}
        </table>
      </td></tr>
      
    {% endif %}
    <tr><td class="attribhead">Message ID:&nbsp;<b>{{ entry.id }}</b>
        &nbsp;&nbsp;&nbsp;&nbsp;Entry time:&nbsp;<b>{{ entry.date }}</b>
        {% if entry.author %}&nbsp;&nbsp;{% translate 'Username' %}:&nbsp;<b>{{ entry.author.get_username }}</b>{% endif %}
        {% if entry.in_reply_to %}
        &nbsp;&nbsp;&nbsp;&nbsp;{% translate 'In reply to' %}:&nbsp;<b><a href="{% url 'flexelog:entry_detail' logbook.name entry.in_reply_to.id %}">{{ entry.in_reply_to.id }}</a></b>
        {% endif %}
        {% if entry.replies.count %}&nbsp;&nbsp;&nbsp;&nbsp;{% translate 'Reply to this' %}:{{ entry|list_replies }}{% endif %}
    </td></tr>
    </td></tr>
    {% if entry.last_modified_date %}
        <tr><td class="attribhead">{% translate 'Last submission' %}:&nbsp;{% translate 'Entry time' %}:&nbsp;<b>{{ entry.last_modified_date }}</b>
        {% if entry.last_modified_author %}&nbsp;&nbsp;{% translate 'Username' %}:&nbsp;<b>{{ entry.last_modified_author.get_username }}</b>{% endif %}
        </td></tr>
    {% endif %}
    <tr>
    <td>
    <table width="100%" cellpadding="0" cellspacing="0">
        {% for attr, val in entry.attrs.items %}
        <tr>
            <td class="attribname" nowrap>{{ attr|capfirst }}:</td>
            <td class="attribvalue">{% if attr in IOptions %}{{ val|icon_show}}{% else %}{{ val|attr_show }}{% endif %}</td>
        </tr>
        {% endfor %}
    </table>
    </td>
    </tr>

    {# EDITOR/VIEWER #}
    {% if encoding and encoding != "markdown" %}
      <tr><td class="encoding">{% translate "Encoding" %}: {{ encoding }}</td></tr>
    {% endif %}
    <tr>
    <td class="messageframe">

        {{ form.text }}
    </td>
    </tr>
    
  </table>

   {% include "flexelog/include/attachments.html" %}

</form>

{% endblock body %}

flexelog/templates/flexelog/entry_list.html
{% extends "flexelog/base.html" %}
{% load static %}

{% block more_head_links %}
 {% if mode == "full" %}
    {{ form.media }}
 {% endif %}
{% endblock more_head_links %}
{% block body %}

<form name="form1" method="GET" action=".">

<table class="frame" cellpadding="0" cellspacing="0">
  {% include "flexelog/include/lb_tabs.html" %}
  {% include "flexelog/include/commands.html" %}
  {% include "flexelog/include/filter_attrs.html"%}
  {% include "flexelog/include/list_modes.html" %}
  {% include "flexelog/include/entry_list_core.html" %}

</table>
</form>
{% endblock body %}

flexelog/templates/flexelog/index.html
{% extends "flexelog/base.html" %}
{% load l10n %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load tz %}

{% block title %}FlexElog Logbook Selection{% endblock %}

{% block more_head_links %}

{% endblock %}

{% block body %}
<table class="selframe" cellspacing="0" align="center">
    <tr>
        <td colspan="13" class="dlgtitle">
            {% translate "Several logbooks are defined on this host" %}<br>
            {% translate "Please select the one to connect to" %}
        </td>
    </tr>
    <tr>
        <th colspan="10" class="seltitle">{% translate "Logbook" %}</th>
        <th class="seltitle">{% translate "Entries" %}</th>
        <th class="seltitle">{% translate "Last submission" %}</th>
    </tr>
    {% for group_name, logbooks in group_logbooks.items %}
        {% if group_logbooks|length > 1 %}
            <tr><td colspan=13 class="selgroup">
                {% if group_name %}{{ group_name }}{% else %}---{% endif %}
            </td></tr>
        {% endif %}
        {% for lb in logbooks %}
            <tr>
                <td colspan="10" class="sellogbook">
                    <a href="{% url 'flexelog:logbook' lb.name %}">{{ lb.name }}</a><br>
                    <span class="selcomment"></span>
                </td>
                <td nowrap class="selentries">{{ lb.entries.count }}</td>
                <td nowrap class="selentries" title="{{ lb.latest_date|localtime }}">{{ lb.latest_date|naturaltime }}</td>
            </tr>
        {% empty %}
            <tr><td>{% translate "No logbook defined on this server" %}</td></tr>
            <tr><td>&nbsp;&nbsp;<a href="{% url 'admin:index' %}">{% translate "Admin" %}</a></tr></td>
        {% endfor %}
    {% empty %}
    <tr><td>{% translate "No logbook defined on this server" %}</td></tr>
    <tr><td>&nbsp;&nbsp;<a href="{% url 'admin:index' %}"><span class="highlight">{% translate "Admin" %}</span></a></tr></td>

    {% endfor %}
    </table>
{% endblock body %}

flexelog/templates/flexelog/search_form.html
{% extends 'flexelog/base.html' %}
{% load i18n %}

{% block title %}
  Fl'og {{ logbook.name }}
{% endblock %}
{% block more_head_links %}
  {{ form.media }}
{% endblock %}

{% block body %}
  <form name="form1" method="GET" action=".">
    <table class="frame" cellpadding="0" cellspacing="0">
      {% include 'flexelog/include/lb_tabs.html' %}
      <tr>
        <td class="menuframe">
          <span class="menu1">
            <input type="submit" value="{% translate 'Search' %}" />&nbsp;&nbsp;
            <input type="reset" value="{% translate 'Reset Form' %}" />&nbsp;&nbsp;
            <input type="submit" name="cmd" value="{% translate 'Back' %}" />&nbsp;&nbsp;
          </span>
        </td>
      </tr>
      <tr>
        <td class="form1">
          <table>
            <tr>
              <td valign="top" class="form1"><b>{{ form.mode.label }}:</b><br>{{ form.mode }}</td>
              <td valign="top" class="form1"><b>{{ form.export_to.label }}:</b><br>{{ form.export_to }}</td>
              <td valign="top" class="form2"><b>{{ form.options.label }}:</b><br>{{ form.options }}
                {% translate 'Display' %}&nbsp;{{ form.npp }} {{ form.npp.label }}</td>
            </tr>
          </table>
        </td>
      </tr>
    <tr><td class="form2"><b>{% translate "Filters" %}:</b>&nbsp;&nbsp;
        <span class="selcomment">({{ regex_message|safe }})</span><br>
        <table width="100%" cellspacing=0>
    <tr><td class="attribname" nowrap width="10%">{% translate "Entry date" %}:</td><td class="attribvalue">
        <table width="100%" cellspacing=0 border=0>
            <tr><td width="1%">{{ form.start_date.label }}:</td><td>{{ form.start_date }}&nbsp;&nbsp;/&nbsp;&nbsp;{{ form.last.label }}: {{ form.last }}</td></tr>
            <tr><td width="1%">{{ form.end_date.label }}:</td><td>{{ form.end_date }}</td></tr>
        </table>  
    {# --------- Entry Attributes ---------------------- #}
        {% for attr_field in form.attr_bound_fields.values %}
        <tr><td class="attribname">{{ attr_field.label }}</td>
            <td class="attribvalue">{{ attr_field }}</td>
        {% endfor %}
    {# --------- #}
    <tr>
        <td class="attribname">{{ form.subtext.label }}:</td>
        <td class="attribvalue">{{ form.subtext }} {{ form.sall }} {{ form.sall.label }}</td>
    </tr>
    <tr>
        <td class="attribvalue"></td>
        <td class="attribvalue">{{ form.casesensitive }} {{ form.casesensitive.label }}
    </tr>  
</table>
  </form>
{% endblock %}

flexelog/templates/flexelog/show_error.html
{% extends "flexelog/base.html" %}
{% load i18n %}

{% block title %}{% translate "ELOG error" %}{% endblock %}

{% block body %}
<center>
<table class="dlgframe" width="50%" cellpadding="1" cellspacing="0"
    <tr>
        <td class="errormsg">{{ message | safe }}</td>
    </tr>
    <tr>
        <td class="errormsg">
            <script language="javascript" type="text/javascript">
                document.write("<button type=button onClick=history.back()>{% translate 'Back' %}</button>"); 
            </script>
        <noscript>{% translate "Please use your browser's back button to go back" %}</noscript>
        </td>
    </tr>
</table>
</center>
{% endblock body %}

flexelog/templates/flexelog/xxxtest.html
{% extends "flexelog/base.html" %}
{% load i18n %}

{% block title %}TEST{% endblock title %}
{% block more_head_links %}
{% endblock more_head_links %}

{% block body %}

<form name="form1" method="POST" action=".">
  {% csrf_token %}
  <table class="frame" cellpadding="0" cellspacing="0">
    {% include "flexelog/include/lb_tabs.html" %}
  <table class="listframe" width="100%" cellspacing="0" cellpadding="0">
  <tr><td>{{ form.as_table }}</td></tr>
  <button type="submit">Submit</button>
  </table>
  </table>
</form>


{% endblock body %}